JESI-3007
jesims/parent pull request #43
Opened 2020-02-06 23:50 UTC by AndreTheHunter

[JESI-3007](https://jesims.atlassian.net/browse/JESI-3007)

2020-02-07 05:38 UTC, AndreTheHunter commented on project.clj
> +                         [thheller/shadow-cljs "2.8.83"]
Our version that works is defined in BS

2020-02-09 23:22 UTC, axrs requested changes

2020-02-09 23:22 UTC, axrs commented on CHANGELOG.md
> +* Update `org.postgresql/postgresql` to `42.2.10`]
```suggestion
* Update `org.postgresql/postgresql` to `42.2.10`
```

2020-02-09 23:26 UTC, axrs approved these changes

2020-02-09 23:31 UTC, merged